import {evaluateAmountExpression} from '@/utils/amount';import {useEffect,useRef,useState} from 'react';import {ArrowLeft,Check,ChevronRight} from 'lucide-react';import {db} from '@/database/db';import {createTransaction} from '@/services/transactions';import {suggest} from '@/services/learning';import type {Account,Category,Person,Flow} from '@/models';import {useNavigate} from 'react-router-dom';export function QuickEntry(){
useEffect(() => {
  navigator.clipboard.readText().then(text => {
    if (text.startsWith("CARINA_TEST|")) {
      const parts = text.split("|");
      alert("收到 Shortcut：" + parts[2] + " / " + parts[1]);
    }
  }).catch(() => {});
}, []);
const nav=useNavigate(),ref=useRef<HTMLInputElement>(null);const[step,setStep]=useState<'input'|'review'>('input'),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[flow,setFlow]=useState<Flow>('expense'),[accounts,setAccounts]=useState<Account[]>([]),[categories,setCategories]=useState<Category[]>([]),[people,setPeople]=useState<Person[]>([]),[accountId,setAccountId]=useState(''),[categoryId,setCategoryId]=useState(''),[personId,setPersonId]=useState(''),[personIds,setPersonIds]=useState<string[]>([]),[isAdvance,setIsAdvance]=useState(false);const getLocalDateTime=()=>{const d=new Date();const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;};const [saving,setSaving]=useState(false),[dateTime,setDateTime]=useState(getLocalDateTime);useEffect(()=>{ref.current?.focus();(async()=>{const[a,c,p]=await Promise.all([db.accounts.filter(x=>!x.isArchived).sortBy('sortOrder'),db.categories.filter(x=>!x.isArchived).sortBy('sortOrder'),db.people.filter(x=>!x.isArchived).sortBy('sortOrder')]);setAccounts(a);setCategories(c);setPeople(p);setAccountId(a[0]?.id??'');setCategoryId(c.find(x=>x.flow==='expense')?.id??c[0]?.id??'')})()},[]);async function desc(v:string){setDescription(v);const s=await suggest(v,flow);if(s.accountId)setAccountId(s.accountId);if(s.categoryId)setCategoryId(s.categoryId);if(s.personId){setPersonId(s.personId);setPersonIds([s.personId])}}function next(){const n=evaluateAmountExpression(amount);if(!description.trim()||!Number.isFinite(n)||n<=0||!accountId||!categoryId)return;setStep('review')}async function save(){setSaving(true);try{const n=evaluateAmountExpression(amount);if(!description.trim()||!Number.isFinite(n)||n<=0||!accountId||!categoryId)return;const selectedPeople=personIds.length?personIds:(personId?[personId]:[]);
if(selectedPeople.length<=1){
await createTransaction({description,amount:n,accountId,categoryId,personId:selectedPeople[0]||undefined,flow,dateTime:new Date(dateTime).getTime(),...(isAdvance&&flow==='expense'?{kind:'advance',advanceStatus:'pending'}:{})});
}else{
const totalCents=Math.round(n*100);
const baseCents=Math.floor(totalCents/selectedPeople.length);
const remainder=totalCents%selectedPeople.length;
for(let i=0;i<selectedPeople.length;i++){
const cents=baseCents+(i<remainder?1:0);
await createTransaction({description,amount:cents/100,accountId,categoryId,personId:selectedPeople[i],flow,dateTime:new Date(dateTime).getTime(),...(isAdvance&&flow==='expense'?{kind:'advance',advanceStatus:'pending'}:{})});
}}setDescription('');setAmount('');setPersonIds([]);setPersonId('');setIsAdvance(false);setDateTime(getLocalDateTime());setStep('input');ref.current?.focus()}finally{setSaving(false)}}const cats=categories.filter(x=>x.flow===flow);return <div className="quick-page"><header className="quick-header"><button className="icon-btn" onClick={()=>nav(-1)}><ArrowLeft/></button><div className="quick-title"><h1>Record</h1><span>QUICK ENTRY</span></div><button className="text-btn" onClick={()=>nav('/')}>完成</button></header>{step==='input'?<div className="quick-form"><div className="segmented"><button className={flow==='expense'?'active':''} onClick={()=>setFlow('expense')}>支出</button><button className={flow==='income'?'active':''} onClick={()=>setFlow('income')}>收入</button></div><div className="smart-grid" style={{display:"grid",gridTemplateColumns:"0.55fr 1fr 1fr",gap:"8px",alignItems:"end"}}><label>Date<input type="date" value={dateTime.slice(0,10)} onChange={e=>setDateTime(`${e.target.value}T${dateTime.slice(11,16)}`)}/></label><label>Time<input type="time" value={dateTime.slice(11,16)} onChange={e=>setDateTime(`${dateTime.slice(0,10)}T${e.target.value}`)}/></label></div><label>Description<input ref={ref} value={description} onChange={e=>desc(e.target.value)} placeholder="例如：午饭、打车、给孩子买书"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^\d.+\-*/×÷()\s]/g,''))} inputMode="decimal" placeholder="0.00"/></label><div className="quick-entry-meta" style={{display:"grid",gridTemplateColumns:"0.55fr 1fr 1fr",gap:"12px",alignItems:"end",marginBottom:"8px"}}>
{flow==='expense'&&<label><span>Advance</span><input className="quick-advance-checkbox" type="checkbox" checked={isAdvance} onChange={e=>setIsAdvance(e.target.checked)} style={{width:"18px",height:"18px",marginTop:"7px"}}/></label>}

</div><div className="smart-grid"><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{cats.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Person<div className="person-picker" style={{display:"flex",flexWrap:"wrap",gap:"8px"}}>{people.map(x=><button type="button" key={x.id} className={personIds.includes(x.id)?"primary":"secondary"} style={{width:"max-content",minWidth:"0",flex:"0 0 auto"}} onClick={()=>{const next=personIds.includes(x.id)?personIds.filter(id=>id!==x.id):[...personIds,x.id];setPersonIds(next);setPersonId(next[0]||"");}}>{x.name}</button>)}</div></label></div><button className="primary" onClick={next}>填好了 <ChevronRight/></button></div>:<div className="review"><div className="review-amount">{flow==='expense'?'−':'+'} ¥{evaluateAmountExpression(amount).toFixed(2)}</div><div className="review-list"><div><span>描述</span><strong>{description}</strong></div><div><span>分类</span><strong>{cats.find(x=>x.id===categoryId)?.name??'—'}</strong></div><div><span>账户</span><strong>{accounts.find(x=>x.id===accountId)?.name??'—'}</strong></div><div><span>人物</span><strong>{personIds.length?personIds.map(id=>people.find(x=>x.id===id)?.name).filter(Boolean).join("、"):(people.find(x=>x.id===personId)?.name??"-")}</strong></div></div><button className="primary" disabled={saving} onClick={save}><Check/>{saving?'保存中…':'确认记账'}</button><button className="secondary" onClick={()=>setStep('input')}>返回修改</button></div>}</div>}